#!/usr/bin/env node

var exec = require('child_process').exec
var open = require('open');

var server = exec('./web-server.js');

server.stdout.on('data', function (data) {
  console.log(data)
});

var reload = exec('./bin/reload -t example');
reload.stdout.on('data', function (data) {
  console.log(data)
});

setTimeout(function() {
  open('http://localhost:8000/example/hello.html');
}, 500);
